services:
  grok2api:
    container_name: grok2api
    image: ghcr.io/chenyme/grok2api:latest
    ports:
      - "0.0.0.0:8100:8000"
    environment:
      TZ: Asia/Shanghai
      LOG_LEVEL: INFO
      SERVER_PORT: 8000
      SERVER_WORKERS: 1
      SERVER_STORAGE_TYPE: local
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
